### ISSUE TITLE
Error when installing latest version of JS Custom

### ISSUE THREAD

**Issue by nwoltman** [Thom1729/Sublime-JS-Custom#72]
Just restarted Sublime to pick up the latest release and got this error:

```
Building JS Custom.sublime-syntax.yaml-macros... (C:\Users\nwolt\AppData\Roaming\Sublime Text 3\Packages\JSCustom\src\syntax\JS Custom.sublime-syntax.yaml-macros)

Traceback (most recent call last):
  File "C:\Users\nwolt\AppData\Roaming\SUBLIM~1\Packages\YAML_M~1\st3\yamlmacros\src\build.py", line 42, in build
    out()
  File "C:\Users\nwolt\AppData\Roaming\SUBLIM~1\Packages\YAML_M~1\st3\yamlmacros\src\engine.py", line 123, in process_macros
  File "C:\Users\nwolt\AppData\Roaming\SUBLIM~1\Packages\YAML_M~1\st3\yamlmacros\src\engine.py", line 123, in <genexpr>
  File "C:\Users\nwolt\AppData\Roaming\SUBLIM~1\Packages\YAML_M~1\st3\yamlmacros\src\engine.py", line 28, in load_macros
    output: 'Optional[StreamType]' = None,
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\nwolt\AppData\Roaming\SUBLIM~1\Packages\YAML_M~1\st3\yamlmacros\lib\include.py", line 3, in <module>
    from yamlmacros import get_loader
ImportError: cannot import name get_loader

[Failed in 0.08 seconds.]
```

**Comment by Thom1729** [comment]
It looks like you're on an older version of [yaml_macros_engine](https://github.com/Thom1729/yaml-macros-engine). JS Custom 2.1.0 requires yaml_macros_engine 2.1.0, which has been out for over a month. I'm not sure why it didn't auto-upgrade. You haven't by any chance had Sublime open continuously since May, have you?

**Comment by Thom1729** [comment]
Try running `Package Control: Satisfy Dependencies` from the command palette.

**Comment by nwoltman** [comment]
> You haven't by any chance had Sublime open continuously since May, have you?

Haha, nope. I guess `yaml_macros_engine` just didn't get updated in time somehow. I restarted Sublime and was able to build successfully (didn't need to run `Package Control: Satisfy Dependencies`).

Though to get it to build I had to comment out my `custom_template_tags` configuration.
With this configuration setting:

```json
"custom_template_tags": {
  "sql": "scope:source.sql",
  "/* sql */": "scope:source.sql"
}
```

I get this error:

```
Building JS Custom.sublime-syntax.yaml-macros... (C:\Users\nwolt\AppData\Roaming\Sublime Text 3\Packages\JSCustom\src\syntax\JS Custom.sublime-syntax.yaml-macros)

Error in macro execution.
  in "<unicode string>", line 4, column 1:
    !apply
    ^ (line: 4)
{'flow_types': True, 'file_extensions': ['js', 'jsx'], 'jsx': True, 'string_object_keys': True, 'name': 'JS Custom - Default', 'custom_template_tags': {'sql': 'scope:source.sql', '/* sql */': 'scope:source.sql'}, 'file_path': 'C:\\Users\\nwolt\\AppData\\Roaming\\Sublime Text 3\\Packages\\JSCustom\\src\\syntax\\JS Custom.sublime-syntax.yaml-macros', 'scope': 'source.js.default'}

Error in macro execution.
  in "<unicode string>", line 6, column 5:
      - !get_extensions Packages/JSCusto ... 
        ^ (line: 6)
{'flow_types': True, 'file_extensions': ['js', 'jsx'], 'jsx': True, 'string_object_keys': True, 'name': 'JS Custom - Default', 'custom_template_tags': {'sql': 'scope:source.sql', '/* sql */': 'scope:source.sql'}, 'file_path': 'C:\\Users\\nwolt\\AppData\\Roaming\\Sublime Text 3\\Packages\\JSCustom\\src\\syntax\\JS Custom.sublime-syntax.yaml-macros', 'scope': 'source.js.default'}

Error in macro execution.
  in "<unicode string>", line 7, column 1:
    !merge
    ^ (line: 7)
{'sql': 'scope:source.sql', '/* sql */': 'scope:source.sql'}

Error in macro execution.
  in "<unicode string>", line 8, column 11:
    contexts: !merge
              ^ (line: 8)
{'sql': 'scope:source.sql', '/* sql */': 'scope:source.sql'}

Error in macro execution.
  in "<unicode string>", line 12, column 35:
      literal-string-template-custom: !foreach
                                      ^ (line: 12)
{'sql': 'scope:source.sql', '/* sql */': 'scope:source.sql'}

Traceback (most recent call last):
  File "C:\Users\nwolt\AppData\Roaming\SUBLIM~1\Packages\YAML_M~1\st3\yamlmacros\src\custom_constructor.py", line 31, in macro_constructor
    return macro(loader, node)
  File "C:\Users\nwolt\AppData\Roaming\SUBLIM~1\Packages\YAML_M~1\st3\yamlmacros\src\get_macro.py", line 71, in macro
    return run_coroutine(result, callback)
  File "C:\Users\nwolt\AppData\Roaming\SUBLIM~1\Packages\YAML_M~1\st3\yamlmacros\src\util.py", line 62, in run_coroutine
    result = generator.send(value)
  File "C:\Users\nwolt\AppData\Roaming\SUBLIM~1\Packages\YAML_M~1\st3\yamlmacros\lib\arguments.py", line 46, in foreach
    raise TypeError('Invalid collection {!r}.'.format(collection))
TypeError: Invalid collection None.

[Failed in 1.49 seconds.]
```

**Comment by Thom1729** [comment]
I've just released 2.1.1 to fix that. `custom_template_tags` is deprecated in 2.1 in favor of `custom_templates`, but it's still supposed to work. There was a bug  in 2.1.0 that broke it, and 2.1.1 should fix it.

**Comment by nwoltman** [comment]
Awesome 👍

I'm still not totally sure what caused the initial error, but everything is working now so I'll close this issue.
